const WRONG_PASSWORD = 'WRONG_PASSWORD';
const NO_ACCOUNT = 'NO_ACCOUNT';
const EMAIL_EXISTS = 'EMAIL_EXISTS';
const NOT_FOUND = 'Not found';

export const ERROR_CODES = {
   EMAIL_EXISTS,
   NO_ACCOUNT,
   NOT_FOUND,
   WRONG_PASSWORD
};